### ISSUE TITLE
App won't use state for user story#5

### ISSUE THREAD

**Issue by mojo9492** [nraynes/the-drinks-on-me#11]
#7 is blocked:
 The way the app is set up will never re-render because we do not useEffect, leaving state useless. 
[This problems exists only when you do not useEffect, because the app has no reference when to render changes and uses last render](https://stackoverflow.com/questions/54069253/usestate-set-method-not-reflecting-change-immediately)

Solution: useEffect inside App.js isntead of a for loop in index.js that prevents react from doing react

**Comment by nraynes** [comment]
Master branch has useEffect in place and a reRendering state that solves this issue.
